import PolygonalNumberTheorem.Core.Basic
import PolygonalNumberTheorem.Core.ModularSquares
import PolygonalNumberTheorem.Legendre.Main
import PolygonalNumberTheorem.Legendre.Ankeny
import PolygonalNumberTheorem.Cauchy.Main
