import GeometryOfNumbers.Core.Basic
import Mathlib.Tactic.IntervalCases
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S05
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S06
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S07
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S08
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S09
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S10
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S11
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S12
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S13
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S14
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S15
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S16
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S17
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S18
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S19
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S20
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S21
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S22
import GeometryOfNumbers.Cauchy.MediumTablesSmall.S23

namespace GeometryOfNumbers

-- GENERATED: suppress style linters (tables are mechanically produced)
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unnecessarySimpa false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
-- This file was generated by splitting a large auto-generated table module
-- into per-`s` shards to keep Lean compilation time bounded.
set_option autoImplicit false
set_option maxRecDepth 4096
set_option maxHeartbeats 2000000
set_option synthInstance.maxHeartbeats 2000000

/-- Medium-regime decomposition for the finite band `5 ≤ s ≤ 23`. -/
lemma cauchy_decomposition_medium_small_le23
    (s : ℕ) (hs5 : 5 ≤ s) (hs23 : s ≤ 23) (n : ℕ) (hn0 : n ≠ 0)
    (hsmall : ¬ n ≤ s - 3) (hmed : n ≤ 108 * (s - 2)) :
    ∃ t u v w r : ℕ,
      r ≤ s - 4 ∧ polygonal s t + polygonal s u + polygonal s v + polygonal s w + r = n := by
  classical
  interval_cases s using hs5, hs23
  ·
    -- s = 5
    have hbound : n ≤ 324 := by simpa using hmed
    let nFin : Fin (324 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s5 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s5_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 6
    have hbound : n ≤ 432 := by simpa using hmed
    let nFin : Fin (432 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s6 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s6_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 7
    have hbound : n ≤ 540 := by simpa using hmed
    let nFin : Fin (540 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s7 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s7_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 8
    have hbound : n ≤ 648 := by simpa using hmed
    let nFin : Fin (648 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s8 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s8_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 9
    have hbound : n ≤ 756 := by simpa using hmed
    let nFin : Fin (756 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s9 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s9_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 10
    have hbound : n ≤ 864 := by simpa using hmed
    let nFin : Fin (864 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s10 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s10_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 11
    have hbound : n ≤ 972 := by simpa using hmed
    let nFin : Fin (972 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s11 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s11_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 12
    have hbound : n ≤ 1080 := by simpa using hmed
    let nFin : Fin (1080 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s12 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s12_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 13
    have hbound : n ≤ 1188 := by simpa using hmed
    let nFin : Fin (1188 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s13 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s13_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 14
    have hbound : n ≤ 1296 := by simpa using hmed
    let nFin : Fin (1296 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s14 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s14_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 15
    have hbound : n ≤ 1404 := by simpa using hmed
    let nFin : Fin (1404 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s15 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s15_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 16
    have hbound : n ≤ 1512 := by simpa using hmed
    let nFin : Fin (1512 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s16 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s16_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 17
    have hbound : n ≤ 1620 := by simpa using hmed
    let nFin : Fin (1620 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s17 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s17_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 18
    have hbound : n ≤ 1728 := by simpa using hmed
    let nFin : Fin (1728 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s18 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s18_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 19
    have hbound : n ≤ 1836 := by simpa using hmed
    let nFin : Fin (1836 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s19 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s19_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 20
    have hbound : n ≤ 1944 := by simpa using hmed
    let nFin : Fin (1944 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s20 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s20_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 21
    have hbound : n ≤ 2052 := by simpa using hmed
    let nFin : Fin (2052 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s21 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s21_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 22
    have hbound : n ≤ 2160 := by simpa using hmed
    let nFin : Fin (2160 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s22 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s22_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
  ·
    -- s = 23
    have hbound : n ≤ 2268 := by simpa using hmed
    let nFin : Fin (2268 + 1) := ⟨n, Nat.lt_succ_of_le hbound⟩
    rcases htu : cauchyMediumSmall_s23 nFin with ⟨t, u, v, w, r⟩
    have hspec := cauchyMediumSmall_s23_spec nFin (by simpa [nFin] using hn0) (by simpa using hsmall)
    rcases (by simpa [htu] using hspec) with ⟨hr, hEq⟩
    exact ⟨t, u, v, w, r, hr, by simpa [nFin] using hEq⟩
end GeometryOfNumbers
