import PolygonalNumberTheorem.Legendre.Main
import PolygonalNumberTheorem.Cauchy.Main

def main : IO Unit := do
  IO.println "Polygonal Number Theorem Project Status"
  IO.println "======================================="
  IO.println ""
  IO.println "This is a lightweight status printout."
  IO.println "It does not prove anything by itself; it just summarizes where the code is."
  IO.println ""
  IO.println "Key invariant: if `lake build` succeeds, then the Lean code typechecks."
  IO.println "There are still `sorry` placeholders in the development files."
  IO.println ""

  IO.println "## Legendre's Three-Square Theorem"
  IO.println ""
  IO.println "  - Entry point: `PolygonalNumberTheorem/Legendre/Main.lean`"
  IO.println "  - Support: `PolygonalNumberTheorem/Legendre/Exceptions.lean`"
  IO.println "  - Recommended: `PolygonalNumberTheorem/Legendre/Ankeny.lean` (Ankeny 1957)"
  IO.println "  - Alternative: `PolygonalNumberTheorem/Legendre/Minkowski.lean` (descent scaffold)"
  IO.println ""
  IO.println "  Notes:"
  IO.println "  - Easy direction is present but incomplete (contains `sorry`)."
  IO.println "  - Hard direction is routed through `minkowski_three_squares` (contains `sorry`)."
  IO.println ""
  IO.println "## Polygonal Number Theorem"
  IO.println ""
  IO.println "  - Entry point: `PolygonalNumberTheorem/Cauchy/Main.lean`"
  IO.println "  - Algebra spine: `PolygonalNumberTheorem/Core/Basic.lean`"
  IO.println ""
  IO.println "  Notes:"
  IO.println "  - `gauss_eureka` and `fermat_polygonal` currently contain `sorry`."
  IO.println "  - Scripts under `Scripts/` and scratch under `Experiments/` are for checking intuition."
  IO.println ""
  IO.println "## Dependencies (from Mathlib)"
  IO.println ""
  IO.println "  Nat.sum_four_squares    -- Lagrange's theorem"
  IO.println "  ZMod.sq_add_sq_zmodEq   -- Pigeonhole for squares mod p"
  IO.println ""
  IO.println "## Roadmap pointers"
  IO.println ""
  IO.println "  - `PROOF_ROADMAP.md` is the current dependency graph."
  IO.println "  - `doc/RecordOfProgress.md` and `doc/TechnicalNotes.md` explain pivots/shelved paths."
