import Covolume.Legendre.Main
import Covolume.Cauchy.Main

def main : IO Unit := do
  IO.println "Covolume Project Status"
  IO.println "======================="
  IO.println ""
  IO.println "This is an automated status summary generated from the library source."
  IO.println "Verification state is defined by the success of the 'lake build' process."
  IO.println "Remaining technical gaps are marked with 'sorry' placeholders."
  IO.println ""

  IO.println "## Legendre's Three-Square Theorem"
  IO.println ""
  IO.println "  - Entry point: `Covolume/Legendre/Main.lean`"
  IO.println "  - Support: `Covolume/Legendre/Exceptions.lean`"
  IO.println "  - Recommended: `Covolume/Legendre/Ankeny.lean` (Ankeny 1957)"
  IO.println "  - Alternative: `Covolume/Legendre/Minkowski.lean` (descent scaffold)"
  IO.println ""
  IO.println "  Notes:"
  IO.println "  - Easy direction is proved: sum of three squares ⇒ not a three-square exception."
  IO.println "  - Hard direction remains scaffolded (contains `sorry`)."
  IO.println "    Current intended route: `Ankeny.lean` (Minkowski + descent), with remaining gaps in:"
  IO.println "    - `exists_ankeny_prime`"
  IO.println "    - `exists_ankeny_b`"
  IO.println "    - `exists_ankeny_representation`"
  IO.println "    - `reduction_to_sum_three_squares`"
  IO.println ""
  IO.println "## Polygonal Number Theorem"
  IO.println ""
  IO.println "  - Entry point: `Covolume/Cauchy/Main.lean`"
  IO.println "  - Algebra spine: `Covolume/Core/Basic.lean`"
  IO.println ""
  IO.println "  Notes:"
  IO.println "  - 'gauss_triangular' and 'fermat_polygonal' currently contain placeholders."
  IO.println "  - Scripts under `Scripts/` and scratch under `Experiments/` are for checking intuition."
  IO.println ""
  IO.println "## Dependencies (from Mathlib)"
  IO.println ""
  IO.println "  Nat.sum_four_squares    -- Lagrange's theorem"
  IO.println "  ZMod.sq_add_sq_zmodEq   -- Pigeonhole for squares mod p"
  IO.println ""
  IO.println "## Roadmap pointers"
  IO.println ""
  IO.println "  - `PROOF_ROADMAP.md` is the current dependency graph."
  IO.println "  - `doc/RecordOfProgress.md` and `doc/TechnicalNotes.md` explain pivots/shelved paths."
